### ISSUE TITLE
Decouple step to create dwellings assignment

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/synthetic-population#9]
To create the dwellings assignment for a given SA2, the script should take as input:

*  A households CSV for the SA2
* LandVic property addresses file(s) that includes the SA2, and
* A mapping from SA2 to the Landvic "regions".

The output should be a households assignments (JSON) to known addresses in that SA2.

**Comment by dhixsingh** [comment]
Refer to notes in #22.

**Comment by wniroshan** [comment]
This is fixed as of commit ff3bccb

To map Vicmap addresses to SA1s and then assign households to addresses run `java -jar addressmapper/target/addressmapper.jar addressmapper.properties -sh` command from `synthetic-population/populationbuilder` directory. This program uses the population files generated with `synthesis.jar`, so the population must be synthesised prior to running this command.

To map addresses to SA1s without mapping households use `-s` command line argument instead of `-sh`. 

If addresses are already mapped to SA1s, households can be assigned to addresses (dwellings) independently by specifying only `-h`.
